# Generated by Django 5.2.1 on 2025-06-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('department', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=250)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
