# Generated by Django 5.2.1 on 2025-06-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
